### ISSUE TITLE
the append should append the end of line, not replacing the syntax in the end of line

### ISSUE THREAD

**Issue by CurlyBytes** [joachimdalen/azdevops-pull-request-utils#10]
hi, i just found out each on every submit new commits on the existing PR its just delete the last appended text, should be the last line of text retain and append the new words instead?

![image](https://user-images.githubusercontent.com/55616292/167685595-f8131959-c417-4129-99d4-29772139b9c6.png)

**Comment by joachimdalen** [comment]
Hi!

Calling this option `append` might have been a design flaw from my side. What the `append` option is intended for is to persist a manual entered description. So that you can enter a description when creting the pull request and then having the pipelne **append** to that text. The way it is right now is that every time the task is called, it will replace any other content added by the task, but keep the original description.

It should not be to much work of adding a new option that will also tell it to append to the content previously appended by the task. 

Would this work better for you?
